[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
[project]
name = "REVHubInterface"
version = "1.3.0"
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
[tool.setuptools]
packages = ["REVHubInterface"]
