on:
  workflow_dispatch:
  push:
    branches:
      - trigger-actions

jobs:
  pyinstaller-build-mac:
    runs-on: macos-latest
    steps:
      # - name: Create Executable
      #   uses: sayyid5416/pyinstaller@v1
      #   with:
      #     python_ver: '3.12'
      #     pyinstaller_ver: '==6.6.0'
      #     spec: 'REVHubInterface-mac.spec'
      #     requirements: 'requirements.txt'
      #     upload_exe_with_name: ''
      #     options: --onefile, --name "REVHubInterface", --windowed,
      # - name: Update Executable
      #   id: artifact_patch_mac
      #   shell: sh
      #   run: |
      #       chmod +x ./dist/REVHubInterface.app/Contents/MacOS/REVHubInterface
      #       chmod +x ./dist/REVHubInterface
      - name: (Install) python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
    
      - name: (Install) python dev tools
        shell: bash
        run: python -m pip install pip wheel setuptools
      
      - name: (Install) dependencies
        shell: sh
        run: 
          python -m pip install pyft232==0.12;
          python -m pip install pyserial==3.5;
          python -m pip install sv-ttk==2.6.0;

      - name: (Install) pyinstaller
        shell: bash
        run: pip install pyinstaller==6.6.0
      
      - name: Create Executable
        id: exec-create
        shell: bash
        run: |
          pyinstaller \
            --clean \
            --noconfirm \
            --dist ./dist \
            \
            "REVHubInterface-mac.spec"
      - name: Create App and DMG
        id: artifact-create
        shell: sh
        run: 
          sh ./scripts/dmg_mac.sh
      - name: (Upload) Executable
        id: artifact_upload
        uses: actions/upload-artifact@v4
        with:
          name: "REVHubInterface Mac"
          path: "./dist"
          compression-level: 6
    
      - name: If executable upload success
        id: exe_uploading
        if: steps.artifact_upload.conclusion == 'success'
        shell: bash
        run: |
          echo "✔️ Executable **_(REVHubInterface Mac)_** uploaded successfully" >> $GITHUB_STEP_SUMMARY
          echo "uploaded='true'" >> $GITHUB_OUTPUT
        
      - name: If executable upload fails
        if: failure() && steps.artifact_upload.conclusion == 'failure'
        shell: bash
        run: |
            echo "::warning title=Failed-Upload::\
            Executable couldn't upload. \
            Check available storage at: 'settings > billing > Storage for Actions and Packages'."
  pyinstaller-build-win:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.6.0'
          spec: 'REVHubInterface.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'REVHubInterface Windows'
          options: --onefile, --name "REVHubInterface", --windowed,
  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.6.0'
          spec: 'REVHubInterface.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'REVHubInterface Linux'
          options: --onefile, --name "REVHubInterface", --windowed,
      
        
    
